### ISSUE TITLE
How to get it to work on Mac

### ISSUE THREAD

**Issue by henrikf01** [joscha0/remove-watermark-studydrive#1]
I don't get it to work on Mac, can you give me an instruction? Thank you!

**Comment by joscha0** [comment]
Have you tried the instructions from the readme? @henrikf01

**Comment by henrikf01** [comment]
I didn’t get it 😅 do you have more clear instructions?

**Comment by joscha0** [comment]
1. download python
2. clone the code
3. run `pip install -r requirements.txt` in terminal
4. rename your pdf to input.pdf
5. run `python removewm.py input.pdf output.pdf 
`

**Comment by henrikf01** [comment]
Thats my whole code from terminal:
Last login: Mon Oct 26 22:50:57 on ttys000
henrik.frank@Macbook-von-Henrik ~ % pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
henrik.frank@Macbook-von-Henrik ~ % python removewm.py input.pdf output.pdf
/usr/local/bin/python: can't open file '/Users/henrik.frank/removewm.py': [Errno 2] No such file or directory
henrik.frank@Macbook-von-Henrik ~ % cd /Users/henrik.frank/Downloads/remove-watermark-studydrive-master
henrik.frank@Macbook-von-Henrik remove-watermark-studydrive-master % pip install -r requirements.txt        
Collecting pikepdf
  Using cached pikepdf-1.19.3.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting lxml>=4.0
  Using cached lxml-4.6.1.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-install-ms671n8d/lxml/setup.py'"'"'; __file__='"'"'/private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-install-ms671n8d/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-pip-egg-info-ppuxsnzu
         cwd: /private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-install-ms671n8d/lxml/
    Complete output (3 lines):
    Building lxml version 4.6.1.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
henrik.frank@Macbook-von-Henrik remove-watermark-studydrive-master % python removewm.py input.pdf output.pdf                            
Traceback (most recent call last):
  File "/Users/henrik.frank/Downloads/remove-watermark-studydrive-master/removewm.py", line 1, in <module>
    import pikepdf
ModuleNotFoundError: No module named 'pikepdf'
henrik.frank@Macbook-von-Henrik remove-watermark-studydrive-master %

**Comment by joscha0** [comment]
you need to be in the folder you downloaded just `cd` into it after you extracted the zip

**Comment by henrikf01** [comment]
I have Cd to the location but I get the error that my pikepdf module is not found, even though I run the requirement.txt 

Traceback (most recent call last):
  File "removewm.py", line 1, in <module>
    import pikepdf
ImportError: No module named pikepdf

**Comment by joscha0** [comment]
`pip install pikepdf`

**Comment by henrikf01** [comment]
If I install it this comes:

    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-install-hm42izou/lxml/setup.py'"'"'; __file__='"'"'/private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-install-hm42izou/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-pip-egg-info-ir5q14_h
         cwd: /private/var/folders/m2/z8tp1qb55j1dvfc6hdj3k2tr0000gn/T/pip-install-hm42izou/lxml/
    Complete output (3 lines):
    Building lxml version 4.6.1.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by joscha0** [comment]
try follow the installation for lxml [here](https://lxml.de/installation.html)

**Comment by henrikf01** [comment]
Thanks! I guess it doesn't work because I use Big Sur...
